# Generated by Django 3.1.12 on 2025-04-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l_pedidos', '0002_auto_20250410_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='l_pedidos.producto'),
        ),
    ]
