# Generated by Django 3.1.12 on 2025-04-10 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('l_pedidos', '0003_auto_20250410_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='l_pedidos.producto'),
        ),
    ]
